### ISSUE TITLE
geoip/geoip v1.14 conflicts with ext-geoip[1.0.8]

### ISSUE THREAD

**Issue by karen-mikaela** [maxmind/geoip-api-php#31]
Hi, i am try install dependenciesm but I got this errors.
  Problem 1
    - Installation request for ext-geoip 1.0.8 -> satisfiable by ext-geoip[1.0.8].
    - geoip/geoip v1.14 conflicts with ext-geoip[1.0.8].
    - Installation request for geoip/geoip ~1.14 -> satisfiable by geoip/geoip[v1.14].

Thank you for any help.

**Comment by oschwald** [comment]
As the error suggests, this module cannot be used when the [GeoIP PECL extension](http://pecl.php.net/package/geoip) is in use.
