### ISSUE TITLE
Notice about non object

### ISSUE THREAD

**Issue by dopesong** [maxmind/geoip-api-php#34]
`geoip_record_by_addr` returned value might be null, but some methods like `geoip_country_code_by_addr` checks for exact `false` returned value.

https://github.com/maxmind/geoip-api-php/blob/352ab1a43124b13878e1dc58ccd16c9d607cae22/src/geoip.inc#L1638

**Comment by oschwald** [comment]
I do agree that this seems suspicious. Are you getting an actual failure from this though? As far as I can tell, the code in question dates back to at least 2007 and I am not aware of any reports of issues due to it.

**Comment by dopesong** [comment]
Yeah we got this on some ips: 

>Notice: Trying to get property of non-object in /home/test/wp-content/plugins/proxies-plugin/vendor/geoip/geoip/src/geoip.inc on line 1639

**Comment by oschwald** [comment]
Thanks! I release 1.16 with a fix.

**Comment by dopesong** [comment]
Glad to know it's fixed. :)
