### ISSUE TITLE
inconsistancy in quotes

### ISSUE THREAD

**Issue by Zen4All** [maxmind/geoip-api-php#36]
why are in  https://github.com/maxmind/geoip-api-php/src/geoipregionvars.php some numbers in the array surrounded by quotes, and some are not?
In thought they all needed to be in quotes
for example
`'AF' => 
  array (
    '01' => 'Badakhshan',
    '02' => 'Badghis',
    '03' => 'Baghlan',
    '05' => 'Bamian',
    '06' => 'Farah',
    '07' => 'Faryab',
    '08' => 'Ghazni',
    '09' => 'Ghowr',
    10 => 'Helmand',
    11 => 'Herat',
    13 => 'Kabol',
    14 => 'Kapisa',
    17 => 'Lowgar',
    18 => 'Nangarhar',
    19 => 'Nimruz',
    23 => 'Kandahar',
    24 => 'Kondoz',
    26 => 'Takhar',
    27 => 'Vardak',
    28 => 'Zabol',
    29 => 'Paktika',
    30 => 'Balkh',
    31 => 'Jowzjan',
    32 => 'Samangan',
    33 => 'Sar-e Pol',
    34 => 'Konar',
    35 => 'Laghman',
    36 => 'Paktia',
    37 => 'Khowst',
    38 => 'Nurestan',
    39 => 'Oruzgan',
    40 => 'Parvan',
    41 => 'Daykondi',
    42 => 'Panjshir',
  ),`

**Comment by oschwald** [comment]
Are you trying to solve a particular problem? That file is automatically generated. The ones with quotes have a leading `0` that needs to be quoted to be interpreted correctly.

**Comment by Zen4All** [comment]
No particular problem just an observation ;) . I was doing a comparison with an older version of the file, and they had all double quotes.
