### ISSUE TITLE
Malta ('MT') missing from country / region list

### ISSUE THREAD

**Issue by benomatis** [maxmind/geoip-api-php#37]
We're using a [Yii implementation](http://www.yiiframework.com/extension/geoip/) of geoip, but people from Malta ('MT') reported it broken.

The error they received was...
> Undefined index MT

...at the following line:
```php
  public static function getRegionName($countryCode, $regionCode) {
    if ($countryCode === null || $regionCode === null) {
      return null;
    }
    return self::$crnMap[$countryCode][$regionCode]; // <--- this is where the error pointed
  }
```

The person who built the extension for Yii used your [geoipregionvars.php file](https://github.com/maxmind/geoip-api-php/blob/master/src/geoipregionvars.php) as its basis, I guess, and when having a look at it, I do miss 'MT'.

What is this list based on, and is there a specific reason why Malta ('MT') (and I'm pretty sure several other countries) aren't on the list?

**Comment by oschwald** [comment]
Our GeoIP Legacy databases do not have regions for Malta. Please use our GeoIP2 databases if you need this functionality. As far as fixing the error, you can just modify the module you are using to guard against `self::$crnMap[$countryCode]` not existing, which is not an issue with this library.

**Comment by benomatis** [comment]
Thanks for coming back so quickly.
