### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by ale5000-git** [maxmind/geoip-api-php#40]
Can you please specify in the description the minimum PHP version needed for the API to work?
My script support also very old versions of PHP so I want include the API only where it works.

**Comment by oschwald** [comment]
We only [test back to 5.3](https://github.com/maxmind/geoip-api-php/blob/master/.travis.yml). Earlier versions likely work, but I am not sure offhand which versions would work and without automated test for them, they are likely to break.
