### ISSUE TITLE
Installation WPML_GeoIP_IPResolver.class.php

### ISSUE THREAD

**Issue by dripppple** [maxmind/geoip-api-php#41]
Hey, I followed your readme but I cant understand what I should do in the **WPML_GeoIP_IPResolver.class.php** 

My site is in english 

> homepage.com

 But when someone from Sweden enter I want it to redirect to 

> homepage.com/sv

You say I should modify the **language_mappings** and **default_language** but to what?

```
   //Array with structure MaxMind Code => WPML Code 
   $this->language_mappings = array(
   'US' => 'en', //USA
   'SE' => 'sv', //Sweden
		);**
```

```
    //Set the default WPML language which is used if no matching language is found
    $this->default_language = 'en';
```

Whats wrong here?

**Comment by oschwald** [comment]
It appears you might be filing the bug report against the wrong API. This API does not provide `WPML_GeoIP_IPResolver.class.php`.
