### ISSUE TITLE
Missing regions in get_time_zone function

### ISSUE THREAD

**Issue by terpfear** [maxmind/geoip-api-php#43]
According to http://dev.maxmind.com/geoip/legacy/mod_geoip2/ it is possible to get a region code of 
"AA", "AP" and "AE" with a "US" country code.  These country/region combinations are missing from the get_time_zone function in /src/timezone.php.

**Comment by oschwald** [comment]
These "regions"/"countries" do not have an associated timezone as they span many time zones. Returning `null` is the expected behavior.

Greg
MaxMind
