### ISSUE TITLE
Wrong detection of the IRELAND ips

### ISSUE THREAD

**Issue by esetuser** [maxmind/geoip-api-php#44]
Hi,

I'm using your latest code with latest GeoIp.dat file.
Some ips, for example,
52.208.219.197, 52.208.234.53, 52.209.60.202, 52.209.69.178, 52.209.239.192, 52.210.87.79 (and more),
gives wrong result on different requests.
the same code is used, but different results received.,..

|| *time* || *ip* || *detected_country* ||
|| 2016-09-10 08:05:32 || 52.208.219.197 || IRL ||
|| 2016-09-10 10:11:18 || 52.208.219.197 || USA ||
|| 2016-09-10 11:29:54 || 52.208.219.197 || USA ||
|| 2016-09-11 00:24:19 || 52.208.219.197 || USA ||
|| 2016-09-11 05:22:19 || 52.208.219.197 || IRL ||
|| 2016-09-11 17:49:02 || 52.208.219.197 || IRL ||

Your help will be nice... (maybe heavy load on the file gives wrong results?)

Code Usage:
`$gi = geoip_open('GeoIP.dat', 0);`
`$country = geoip_country_name_by_addr($gi, $ipAddress);`
`geoip_close($gi);`

**Comment by oschwald** [comment]
Are you sure that the database was not updated during this time?

**Comment by esetuser** [comment]
100% percent 
this error is happening all the time.

**Comment by esetuser** [comment]
More examples:

|| *time* || *ip* || *detected_country* ||
|| 2016-07-27 19:57:55 || 149.56.15.144 || USA ||
|| 2016-08-23 21:17:36 || 149.56.15.144 || USA ||
|| 2016-08-24 21:41:50 || 149.56.15.144 || USA ||
|| 2016-08-29 04:06:15 || 149.56.15.144 || USA ||
|| 2016-08-30 16:53:02 || 149.56.15.144 || CAN ||
|| 2016-09-01 09:15:45 || 149.56.15.144 || CAN ||
|| 2016-09-01 19:10:50 || 149.56.15.144 || USA ||
|| 2016-09-02 05:11:22 || 149.56.15.144 || USA ||
|| 2016-09-02 18:52:32 || 149.56.15.144 || USA ||
|| 2016-09-13 22:12:48 || 149.56.15.144 || CAN ||
|| 2016-09-14 20:40:57 || 149.56.15.144 || CAN ||
|| 2016-09-14 20:41:12 || 149.56.15.144 || USA ||

|| *time* || *ip* || *detected_country* ||
|| 2016-08-24 05:31:47 || 139.162.194.36 || GBR ||
|| 2016-08-24 05:31:52 || 139.162.194.36 || USA ||
|| 2016-08-24 05:31:56 || 139.162.194.36 || GBR ||
|| 2016-09-14 21:06:01 || 139.162.194.36 || GBR ||
|| 2016-09-14 21:37:25 || 139.162.194.36 || USA ||
|| 2016-09-15 01:24:55 || 149.56.15.144 || USA ||

**Comment by esetuser** [comment]
Database were old... u right
