### ISSUE TITLE
strpos(): Non-string needles will be interpreted as strings in the future.

### ISSUE THREAD

**Issue by DavideArgellati** [maxmind/geoip-api-php#54]
Is there a possibility to fix this, unfortunately we can't switch to version 2 at the moment.  

strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
Line: 840 of  vendor/pear/net_geoip/Net/GeoIP.php

**Comment by oschwald** [comment]
You seem to be using the [PEAR package](https://pear.php.net/manual/en/package.networking.net-geoip.php), which is a different library than this one and is not maintained by MaxMind.
