### ISSUE TITLE
Not compatible with PHP 8.0.0 RC1

### ISSUE THREAD

**Issue by francislavoie** [maxmind/geoip-api-php#57]
I'm still using this extension with a legacy app, and we're trying to test against PHP 8 for future compat and seeing if the JIT helps us with a particular workload.

If there any chance that this'll be updated to support PHP 8? It seems like a not-insignificant amount of work to use https://github.com/maxmind/GeoIP2-php since the databases aren't shipped with it.

**Comment by oschwald** [comment]
Thanks for reporting this. We'll try to get a fix out for it.

Please note that the Legacy database format will be [discontinued in May of 2022](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/). If you haven't already, I would suggest making plans to upgrade to GeoIP2.

**Comment by oschwald** [comment]
Oh, one more thing: I noticed that you mentioned "extension". Are you referring to the PECL extension? That is maintained by a third party and different than this API. You would need to contact the maintainer about that.

**Comment by francislavoie** [comment]
Oh - you're right, I wrote too fast. I looked on the pecl site and it didn't have a github link so I googled for it and found this, so assumed this was the C extension. Didn't realize there was a pure PHP implementation.

Sorry for the confusion!
