### ISSUE TITLE
CentOS7 and  PHP8.0   geoip.c: ‘OnUpdateDirectory’:

### ISSUE THREAD

**Issue by WPFS** [maxmind/geoip-api-php#59]
[root@dev geoip-1.1.1]# make
/bin/sh /usr/local/src/a/geoip-1.1.1/libtool --mode=compile cc -I. -I/usr/local/src/a/geoip-1.1.1 -I/usr/local/src/a/geoip-1.1.1/include -I/usr/local/src/a/geoip-1.1.1/main -I/usr/local/src/a/geoip-1.1.1 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -c /usr/local/src/a/geoip-1.1.1/geoip.c -o geoip.lo
mkdir .libs
 cc -I. -I/usr/local/src/a/geoip-1.1.1 -I/usr/local/src/a/geoip-1.1.1/include -I/usr/local/src/a/geoip-1.1.1/main -I/usr/local/src/a/geoip-1.1.1 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/a/geoip-1.1.1/geoip.c  -fPIC -DPIC -o .libs/geoip.o
/usr/local/src/a/geoip-1.1.1/geoip.c: 在函数‘OnUpdateDirectory’中:
/usr/local/src/a/geoip-1.1.1/geoip.c:141:75: 错误：expected ‘)’ before ‘TSRMLS_CC’
  return OnUpdateString(entry, new_value, mh_arg1, mh_arg2, mh_arg3, stage TSRMLS_CC);
                                                                           ^
/usr/local/src/a/geoip-1.1.1/geoip.c: 在函数‘zif_geoip_db_avail’中:
/usr/local/src/a/geoip-1.1.1/geoip.c:264:44: 错误：expected ‘)’ before ‘TSRMLS_CC’
  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &edition) == FAILURE) {
                                            ^
/usr/local/src/a/geoip-1.1.1/geoip.c:264:44: 错误：提供给函数‘zend_parse_parameters’的实参太少
In file included from /usr/local/php/include/php/main/php.h:35:0,
                 from /usr/local/src/a/geoip-1.1.1/geoip.c:32:
/usr/local/php/include/php/Zend/zend_API.h:304:22: 附注：在此声明
 ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
                      ^
/usr/local/src/a/geoip-1.1.1/geoip.c:270:25: 错误：expected ‘)’ before ‘TSRMLS_CC’
   php_error_docref(NULL TSRMLS_CC, E_WARNING, "Database type given is out of bound.");

make: *** [geoip.lo] 错误 1

**Comment by oschwald** [comment]
It appears that you are trying to use the [GeoIP Legacy PECL package](https://pecl.php.net/package/GEOIP), which is not maintained by MaxMind. This repo is for the pure PHP implementation.

That said, we are [retiring the GeoIP Legacy databases in less than a year](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/#:~:text=We%20are%20planning%20to%20retire,databases%20at%20your%20earliest%20convenience.). I would suggest upgrading to our GeoIP2 databases and [API](https://github.com/maxmind/GeoIP2-php).
