### ISSUE TITLE
Fatal error: Cannot redeclare geoip_country_code_by_name() when PHP geoip extension is enabled

### ISSUE THREAD

**Issue by daigo75** [maxmind/geoip-api-php#6]
If file geoip.inc is loaded in an environment where the geoip extension is enabled, the following error appears:

```
Fatal error: Cannot redeclare geoip_country_code_by_name()
```

This is due to the fact that both the geoip.inc and geoip extension declare such function, and no check is made to ensure that it doesn't already exists.

**Comment by TokyoDesu** [comment]
i can solved this problem i Got to my CPanel Choose version of PHP and select the actual and disable in the options geoip extension.

Now all work good =).

Only need check your hosting cpanel or if you have a vps only change your php.ini
